from random import randint

# SCREEN
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600

# PADDLE
L_PADDLE_X_COORDINATES = -470
R_PADDLE_X_COORDINATES = 460
PADDLE_STRETCH_WIDTH = 1
PADDLE_STRETCH_LEN = 5
Y_PADDLE_TOP_COORDINATES = SCREEN_HEIGHT / 2 - 50
Y_PADDLE_BOTTOM_COORDINATES = -SCREEN_HEIGHT / 2 + 65
PADDLE_SPEED = 40
PADDLE_WIDTH = PADDLE_STRETCH_WIDTH * 20
PADDLE_LENGTH = PADDLE_STRETCH_LEN * 20

# BALL
STRETCH_WIDTH_BALL = 1.5
STRETCH_LEN_BALL = 1.5
LIST_OF_BALL_DIRECTIONS = [randint(20, 60), randint(300, 340), randint(120, 160), randint(200, 240)]
BALL_SPEED = 3
BALL_SPEED_INCREASE_INCREMENT = 0.1
Y_BALL_TOP_COORDINATES = SCREEN_HEIGHT / 2 - 18
Y_BALL_BOTTOM_COORDINATES = -SCREEN_HEIGHT / 2 + 30
BALL_WIDTH = STRETCH_WIDTH_BALL * 20
HIT_DISTANCE_FROM_PADDLE = PADDLE_LENGTH/2 + 10

#SCOREBOARD
L_SCORE_POSITION = (-100,200)
R_SCORE_POSITION = (50,200)
MAX_GOALS = 3